#!/bin/bash

allow_server() {
  local PROTOCOL=$1
  local INTERFACE=$2
  local PORT=$3

  iptables -I INPUT -p "$PROTOCOL" -i "$INTERFACE" --dport "$PORT" -m state --state NEW,ESTABLISHED -j ACCEPT
  iptables -I OUTPUT -p "$PROTOCOL" -o "$INTERFACE" --sport "$PORT" -m state --state ESTABLISHED -j ACCEPT
}

iptables -F INPUT
iptables -F OUTPUT
iptables -F FORWARD
iptables -F DOCKER
iptables -F DOCKER-ISOLATION-STAGE-1
iptables -F DOCKER-ISOLATION-STAGE-2
iptables -F DOCKER-USER
iptables -F -t nat
iptables -X DOCKER
iptables -X DOCKER-ISOLATION-STAGE-1
iptables -X DOCKER-ISOLATION-STAGE-2
iptables -X DOCKER-USER

echo '{"iptables": false}' > /etc/docker/daemon.json

echo -e "IMPORTANT: \nPlease specify SSH connection parameters. This will prevent ssh connection to be closed.\n"

echo "Protocol:"
read -r PROTOCOL
echo "Port:"
read -r PORT

allow_server "$PROTOCOL" "$1" "$PORT"

iptables-save > /etc/iptables/rules.v4
iptables-restore < /etc/iptables/rules.v4
netfilter-persistent reload

sysctl -p /etc/sysctl.conf