#!/bin/bash

cd iptables_utils
./install.sh
cd ..

./install_dependencies

cd cd_utils
./install.sh
cd ..

cd docker_utils
./install.sh
cd ..

cd knock_utils
./install.sh
cd ..

cd monitor_utils
./install.sh
cd ..

cd reverse_proxy
./install.sh
cd ..

. /usr/local/lib/iptables_utils/allow_client.sh

read -p "Public network name: " PUBLIC_NETWORK

allow_client "tcp" "$PUBLIC_NETWORK" "80"
allow_client "tcp" "$PUBLIC_NETWORK" "443"
allow_client "udp" "$PUBLIC_NETWORK" "53"
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP
iptables-save > /etc/iptables/rules.v4

nano /etc/sysctl.conf
sysctl -p

clear

echo "Listo. Solo queda agregar al daemon.json de docker la ip del registry. Si tu red por defecto no es eth0, edita /root/default-infrastructure"