#!/bin/bash

apt update
apt upgrade
apt install ca-certificates curl gnupg
apt install knockd
apt install nodejs
apt install iptables-persistent

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
apt update
apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

nano /etc/default/knockd
systemctl start knockd
systemctl enable knockd

iptables -F INPUT
iptables -F OUTPUT
iptables -F FORWARD
iptables -F DOCKER
iptables -F DOCKER-ISOLATION-STAGE-1
iptables -F DOCKER-ISOLATION-STAGE-2
iptables -F DOCKER-USER
iptables -F -t nat
iptables -X DOCKER
iptables -X DOCKER-ISOLATION-STAGE-1
iptables -X DOCKER-ISOLATION-STAGE-2
iptables -X DOCKER-USER

echo '{"iptables": false}' > /etc/docker/daemon.json

iptables-allow_server

iptables-save > /etc/iptables/rules.v4
iptables-restore < /etc/iptables/rules.v4
netfilter-persistent reload

sysctl -p /etc/sysctl.conf