#!/bin/bash

install_dependencies() {
  apt update -y
  apt upgrade -y
  apt install -y jq ca-certificates curl gnupg knockd iptables-persistent

  nano /etc/default/knockd
  systemctl start knockd
  systemctl enable knockd
}

install_dependencies