#!/bin/bash

./install_dependencies

cd iptables_utils
./install.sh
cd ..
read -p "Public network name: " PUBLIC_NETWORK

./configure_network $PUBLIC_NETWORK

cd cd_utils
./install.sh
cd ..

cd docker_utils
./install.sh
cd ..

cd knock_utils
./install.sh
cd ..

cd monitor_utils
./install.sh
cd ..

cd reverse_proxy
./install.sh
cd ..

. /usr/local/lib/iptables_utils/allow_client.sh

allow_client "tcp" "$PUBLIC_NETWORK" "80"
allow_client "tcp" "$PUBLIC_NETWORK" "443"
allow_client "udp" "$PUBLIC_NETWORK" "53"
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP
iptables-save > /etc/iptables/rules.v4

nano /etc/sysctl.conf
sysctl -p

clear

echo "Ready. If your default network is not actually eth0, edit /root/default-infrastructure"
