#!/bin/bash

. /usr/local/lib/docker_utils/internal_docker_run.sh
. /usr/local/lib/docker_utils/get_container_ip.sh
. /usr/local/lib/monitor_utils/add_prometheus_target.sh

function run_deploy() {
  local IMAGE_NAME=$1
  local CONTAINER_NAME=$2
  local SERVICE_PORT=$3
  local CONTAINER_NETWORK=$4
  local SERVICE_NAME=$5
  local MEMORY=${6:-"100m"}
  local CPU=${7:-".1"}
  local DOCKER_REGISTRY_IP=$(get_container_ip "registry" "internal")
  local FULL_IMAGE_NAME="$DOCKER_REGISTRY_IP:5000/$IMAGE_NAME"
  local RESOURCES="--memory=$MEMORY --cpus=$CPU"
  local CONTAINER_IP=$(internal_docker_run "$FULL_IMAGE_NAME" "$CONTAINER_NAME" "$SERVICE_PORT" "$CONTAINER_NETWORK" "$RESOURCES")

  add_prometheus_target "$CONTAINER_IP" "$SERVICE_NAME"
}

run_deploy "$1" "$2" "$3" "$4" "$5" "$6" "$7"