#!/bin/bash

. /usr/local/lib/docker_utils/secure_docker_run.sh
. /usr/local/lib/docker_utils/internal_docker_run.sh
. /usr/local/lib/iptables_utils/allow_client.sh
. /usr/local/lib/reverse_proxy/create_reverse_proxy.sh

PUBLIC_INTERFACE="eth0"

function create_docker_registry() {
  secure_docker_run "registry" "5000" "registry" "registry:2" "${PUBLIC_INTERFACE}" "2001" "1001 2002 3003" "tcp"
  allow_client "tcp" "internal" "5000"
}

function create_deploy_service() {
    mkdir -p /root/deploy-service/deploy/pending || true
    mkdir -p /root/deploy-service/deploy/done || true
    rm /root/deploy-service/deploy/instances.json

    EXTRA_OPTS="--mount type=bind,source=/root/deploy-service/deploy/pending,target=/etc/pending-deploys"
    secure_docker_run "deploy-service" "8080" "deploy_service" "deploy-service" "${PUBLIC_INTERFACE}" "2002" "4004 5005 6006" "tcp" "$EXTRA_OPTS"
}

function create_prometheus_server() {
  rm /etc/adlamin/monitor/prometheus.yml || true
  cp /etc/adlamin/monitor/empty_prometheus.yml /etc/adlamin/monitor/prometheus.yml
  internal_docker_run "prom/prometheus" "prometheus" "9090" "internal" "-v /etc/adlamin/monitor/prometheus.yml:/etc/prometheus/prometheus.yml -v /etc/adlamin/monitor/data:/prometheus"
}

create_reverse_proxy "dmz" "80" "dmz" "nginx" "tcp" "${PUBLIC_INTERFACE}" "80"
create_docker_registry
create_deploy_service
create_prometheus_server