#!/bin/bash

. /usr/local/lib/docker_utils/secure_docker_run.sh
. /usr/local/lib/iptables_utils/allow_client.sh
. /usr/local/lib/reverse_proxy/create_reverse_proxy.sh

PUBLIC_INTERFACE="eth0"

function create_docker_registry() {
  secure_docker_run "registry" "5000" "registry" "registry:2" "${PUBLIC_INTERFACE}" "2001" "1001 2002 3003" "tcp"
  allow_client "tcp" "internal" "5000"
}

create_docker_registry
create_reverse_proxy "dmz" "80" "dmz" "nginx" "tcp" "${PUBLIC_INTERFACE}" "80"

mkdir -p /root/deploy-service/deploy/pending
mkdir -p /root/deploy-service/deploy/done

EXTRA_OPTS="--mount type=bind,source=/root/deploy-service/deploy/pending,target=/etc/pending-deploys"
secure_docker_run "deploy-service" "8080" "deploy_service" "deploy-service" "${PUBLIC_INTERFACE}" "2002" "4004 5005 6006" "tcp" "$EXTRA_OPTS"
